repos:
  - repo: builtin
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: c2bc67fe8f8f549cc489e00ba8b45aa18ee713b1 # v3.8.1
    hooks:
      - id: prettier

  - repo: https://github.com/crate-ci/typos
    rev: 57b11c6b7e54c402ccd9cda953f1072ec4f78e33 # v1.43.5
    hooks:
      - id: typos

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: f761d025eb06bcd6a45bf152ba3593c9b8ad9a9b # 0.36.2
    hooks:
      - id: check-github-workflows
      - id: check-renovate

  - repo: https://github.com/rhysd/actionlint
    rev: 393031adb9afb225ee52ae2ccd7a5af5525e03e8 # v1.7.11
    hooks:
      - id: actionlint

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: b546b77c44c466a54a42af5499dcc0dcc1a3193f # v1.22.0
    hooks:
      - id: zizmor
        args: [--fix=safe]

  - repo: https://github.com/golangci/golangci-lint
    rev: 5d1e709b7be35cb2025444e19de266b056b7b7ee # v2.10.1
    hooks:
      - id: golangci-lint-full

  - repo: https://github.com/aleksac/hadolint-py
    rev: 458cb25edf664682e3e856a53a2f9af33e068297 # v2.14.0
    hooks:
      - id: hadolint
